name: 'Returns version'
description: 'Returns new version using analyses made by GitVersion'

outputs:
  version:
    description: "Version number"
    value: ${{ env.GitVersion_SemVer }}
    
runs:
  using: "composite"
  steps:
    - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7