name: 'Returns version'
description: 'Returns new version using analyses made by GitVersion'

outputs:
  version:
    description: "Version number"
    value: ${{ steps.output-version.outputs.output-version }}
    
runs:
  using: "composite"
  steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7

    - id: output-version
      run: echo "output-version=${{ env.GitVersion_SemVer }}" >> $GITHUB_OUTPUT
      shell: bash