name: 'Deploy service to k8s'

description: 'Deploy image from github registry to the k8s cluster. '
inputs:
  kubeconfig:  
    description: 'base64 encoded string containng kubeconfig file. Necessary to acces cluser from kubectl'
    required: true
  cluster-name:  
    description: 'k8s culster name.'
    required: true
  image-tag:  
    description: 'Tag of image from gitHub container registry'
    required: true
  deploy-file:  
    description: 'Path to deploy resource yaml file. '
    required: true
  service:  
    description: 'Folder where Dockerfile is located'
    required: true

runs:
  using: "composite"
  steps:
  - name: Create kubeconfig
    shell: bash
    run: |
      mkdir ${HOME}/.kube
      echo ${{ inputs.kubeconfig }} | base64 --decode > ${HOME}/.kube/config

  - name: Set Context
    shell: bash
    run: kubectl config use-context ${{ inputs.cluster-name }}

  - name: Set tag to deployment
    shell: bash
    run: |
      sed -i 's/<image_tag>/${{ inputs.image-tag }}/g' ${{ inputs.deploy-file }}

  - name: Deploy to K8s
    shell: bash  
    run: |
      kubectl apply -f ${{ inputs.deploy-file }}