name: 'Build and push to ActAware GHCR'
description: 'Build and push docker file and push to ActAware GitHub Container Registry'
inputs:
  ghcr-actor:  
    description: 'GitHub Container Registry Actor'
    required: true
  ghcr-token:  
    description: 'GitHub Container Registry Token'
    required: true
  image-name:  
    description: 'Image name'
    required: true
  image-version:  
    description: 'Image version'
    required: true
  dockerfile:  
    description: 'Dockerfile location'
    required: true
  context:
    description: 'Context folder'
    required: false
    default: ""
  container-registry:
    description: 'Container registry URL'
    required: false
    default: ghcr.io
  push:
    description: 'Push to Container'
    required: false
    default: false
   
runs:
  using: "composite"
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.container-registry }}
        username: ${{ inputs.ghcr-actor }}
        password: ${{ inputs.ghcr-token }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v2
      with:
        images: ${{ inputs.container-registry }}/${{ inputs.image-name }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}},value=${{ inputs.image-version }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
