name: 'Build and push to ActAware GHCR'
description: 'Build and push docker file and push to ActAware GitHub Container Registry'
inputs:
  ghcr-actor:  
    description: 'GitHub Container Registry Actor'
    required: true
  ghcr-token:  
    description: 'GitHub Container Registry Token'
    required: true
  image-name:  
    description: 'Image name'
    required: true
  version:  
    description: 'Image version'
    required: true
  dockerfile-dir:  
    description: 'Folder where Dockerfile is located'
    required: true
   
env:
  REGISTRY: ghcr.io
  
jobs:
  build:
    runs-on: ubuntu-latest

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ inputs.ghcr-actor }}
          password: ${{ inputs.ghcr-token }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ inputs.image-name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}},value=${{ inputs.version }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.dockerfile-dir }}
          file: ${{ inputs.dockerfile-dir }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
