name: 'Restore and cache nugets'
description: 'Restore and cache nugets'

inputs:
  root:  
    description: 'folder/project to restore'
    required: true
  token:  
    description: 'nuget auth token'
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        source-url: https://nuget.pkg.github.com/Actaware/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ inputs.token }}

    - uses: actions/download-artifact@v3
      with:
        name: nugets-cache
        path: ./src/_packages_cache

    - name: Restore dependencies
      run: dotnet restore ${{ inputs.root }} --packages ./src/_packages_cache

    - uses: actions/upload-artifact@v3
      with:
        name: nugets-cache
        path: ./src/_packages_cache
